spring:
  application:
    name: spring-ai-demo
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    ollama:
      chat:
        enabled: false
    openai:
      chat:
        enabled: true
  datasource:
    name: chatlog
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"