spring:
  application:
    name: spring-ai-demo
  config:
    import: "optional:classpath:/creds.yaml"
  ai:
    ollama:
      chat:
        enabled: false
    openai:
      chat:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"